# Generated by Django 4.2.4 on 2023-08-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id_transaction', models.AutoField(primary_key=True, serialize=False)),
                ('sender_name', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('typetransaction', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('sens_transaction', models.CharField(max_length=100)),
            ],
        ),
    ]
