# Generated by Django 4.2.4 on 2023-08-11 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serviceFinance', '0001_initial'),
        ('serviceRequette', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='id_requette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_id', to='serviceRequette.requette'),
        ),
    ]
