# Generated by Django 4.2.4 on 2023-08-20 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceFinance', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='id_requette',
        ),
    ]
