# Generated by Django 4.2.4 on 2023-08-21 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceRequette', '0007_alter_requette_sens_requette_and_more'),
        ('serviceFinance', '0003_remove_transaction_id_requette'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sens_transaction',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='typetransaction',
        ),
        migrations.AddField(
            model_name='transaction',
            name='requette_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requette', to='serviceRequette.requette'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(max_length=200),
        ),
    ]
