# Generated by Django 4.2.4 on 2023-08-21 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceRequette', '0007_alter_requette_sens_requette_and_more'),
        ('serviceFinance', '0005_remove_transaction_requette_id_transaction_requette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='requette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requette', to='serviceRequette.requette'),
        ),
    ]
