# Generated by Django 4.2.4 on 2023-08-22 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceFinance', '0006_alter_transaction_requette'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='requette',
        ),
    ]
