# Generated by Django 4.2.4 on 2023-08-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceFinance', '0009_remove_transaction_requette_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='typetransaction',
            field=models.CharField(max_length=100),
        ),
    ]
