# Generated by Django 4.2.4 on 2023-08-22 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceRequette', '0009_alter_requette_id_requette'),
        ('serviceFinance', '0011_rename_receiver_name_transaction_id_requette_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='id_requette',
        ),
        migrations.AddField(
            model_name='transaction',
            name='requette',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='serviceRequette.requette'),
        ),
    ]
