# Generated by Django 4.2.4 on 2023-08-22 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceRequette', '0009_alter_requette_id_requette'),
        ('serviceFinance', '0012_remove_transaction_id_requette_transaction_requette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='requette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceRequette.requette'),
        ),
    ]
