# Generated by Django 4.2.4 on 2023-08-11 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requette',
            fields=[
                ('id_requette', models.AutoField(primary_key=True, serialize=False)),
                ('typerequette', models.CharField(choices=[('valeur_1', 'Retraire'), ('valeur_2', 'Depôt')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('sens_requette', models.CharField(max_length=100)),
                ('receiver_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='app.utilisateur')),
                ('sender_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='app.utilisateur')),
            ],
        ),
    ]
