# Generated by Django 4.2.4 on 2023-08-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceRequette', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requette',
            name='sens_requette',
            field=models.CharField(choices=[('valeurt_1', 'UBA=>UBA'), ('valeurt_2', 'UBA=>OM'), ('valeurt_3', 'UBA=>MOMO'), ('valeurt_4', 'OM=>UBA'), ('valeurt_5', 'OM=>MOMO'), ('valeurt_6', 'OM=>OM'), ('valeurt_7', 'MOMO=>UBA'), ('valeurt_8', 'MOMO=>MOMO'), ('valeurt_9', 'MOMO=>OM')], max_length=100),
        ),
    ]
