# Generated by Django 4.2.4 on 2023-08-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceRequette', '0002_alter_requette_sens_requette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requette',
            name='sens_requette',
            field=models.CharField(choices=[('UBA=>UBA', 'UBA=>UBA'), ('UBA=>OM', 'UBA=>OM'), ('UBA=>MOMO', 'UBA=>MOMO'), ('OM=>UBA', 'OM=>UBA'), ('OM=>MOMO', 'OM=>MOMO'), ('OM=>OM', 'OM=>OM'), ('MOMO=>UBA', 'MOMO=>UBA'), ('MOMO=>MOMO', 'MOMO=>MOMO'), ('MOMO=>OM', 'MOMO=>OM')], max_length=100),
        ),
        migrations.AlterField(
            model_name='requette',
            name='typerequette',
            field=models.CharField(choices=[('Retraire', 'Retraire'), ('Depôt', 'Depôt')], max_length=100),
        ),
    ]
