# Generated by Django 4.2.4 on 2023-08-20 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('serviceRequette', '0004_remove_requette_receiver_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requette',
            name='receiver_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='app.utilisateur'),
        ),
        migrations.AlterField(
            model_name='requette',
            name='sender_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='app.utilisateur'),
        ),
    ]
