# Generated by Django 4.2.4 on 2023-08-20 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceRequette', '0005_alter_requette_receiver_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requette',
            old_name='receiver_number',
            new_name='receiver_name',
        ),
        migrations.RenameField(
            model_name='requette',
            old_name='sender_number',
            new_name='sender_name',
        ),
    ]
