# Generated by Django 4.2.4 on 2023-08-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceRequette', '0007_alter_requette_sens_requette_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requette',
            name='id_requette',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
