# Generated by Django 4.2.4 on 2023-08-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceRequette', '0009_alter_requette_id_requette'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requette',
            name='status',
        ),
        migrations.AlterField(
            model_name='requette',
            name='amount',
            field=models.DecimalField(decimal_places=1, max_digits=100),
        ),
        migrations.AlterField(
            model_name='requette',
            name='typerequette',
            field=models.CharField(default='DEPOT', max_length=100),
        ),
    ]
