# Generated by Django 4.2.4 on 2023-08-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceRequette', '0010_remove_requette_status_alter_requette_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requette',
            name='status',
            field=models.CharField(default='DEPOT', max_length=100),
        ),
    ]
