# Generated by Django 4.2.4 on 2023-08-30 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceRequette', '0013_remove_requette_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requette',
            name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='requette',
            name='sender_name',
        ),
    ]
