# Generated by Django 4.2.4 on 2023-08-30 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceRequette', '0016_alter_requette_receiver_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requette',
            name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='requette',
            name='sender_name',
        ),
    ]
