version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=montestbd
      - POSTGRES_USER=ibrahim_chakour
      - POSTGRES_PASSWORD=chakour1234

  web:
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
