version: "3"
services:
  db:
    image: postgres
    environment:
     # - DB_HOST = 127.0.0.1
      - POSTGRES_DB=montestbd
      - POSTGRES_USER=ibrahim_chakour
      - POSTGRES_PASSWORD=chakour1234
    ports:
      - "5432:5432"


  web:
    build: .
    command: python manage.py runserver 127.0.0.1:8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
   #   - DB_HOST = 127.0.0.1
      - POSTGRES_DB=montestbd
      - POSTGRES_USER=ibrahim_chakour
      - POSTGRES_PASSWORD=chakour1234
    depends_on:
      - db
