# Generated by Django 4.2.4 on 2023-08-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_utilisateur', models.CharField(max_length=100)),
                ('numero_telephone', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('courriel', models.EmailField(max_length=254)),
                ('operateur', models.CharField(max_length=100)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
